class Constants(object):
    """
    Описание все используемых в проекте констант
    """

    BALCONY_BALCONY_TYPE = 'balcony'
    LOGGIA_BALCONY_TYPE = 'loggia'
    BALCONY_AND_LOGGIA_BALCONY_TYPE = 'balcony_and_loggia'
    TWO_BALCONIES_BALCONY_TYPE = 'two_balconies'
    THREE_BALCONIES_BALCONY_TYPE = 'three_balconies'
    FOUR_BALCONIES_BALCONY_TYPE = 'four_balconies'
    TWO_LOGGIAS_BALCONY_TYPE = 'two_loggias'
    THREE_LOGGIAS_BALCONY_TYPE = 'three_loggias'
    FOUR_LOGGIAS_BALCONY_TYPE = 'four_loggias'
    FIVE_LOGGIAS_BALCONY_TYPE = 'five_loggias'
    TERRACE_BALCONY_TYPE = 'terrace'
    BALCONY_AND_TERRACE_BALCONY_TYPE = 'balcony_and_terrace'
    TWO_BALCONIES_AND_TERRACE_BALCONY_TYPE = 'two_balconies_and_terrace'

    BALCONY_TYPES = [
        BALCONY_BALCONY_TYPE,
        LOGGIA_BALCONY_TYPE,
        BALCONY_AND_LOGGIA_BALCONY_TYPE,
        TWO_BALCONIES_BALCONY_TYPE,
        THREE_BALCONIES_BALCONY_TYPE,
        FOUR_BALCONIES_BALCONY_TYPE,
        TWO_LOGGIAS_BALCONY_TYPE,
        THREE_LOGGIAS_BALCONY_TYPE,
        FOUR_LOGGIAS_BALCONY_TYPE,
        FIVE_LOGGIAS_BALCONY_TYPE,
        TERRACE_BALCONY_TYPE,
        BALCONY_AND_TERRACE_BALCONY_TYPE,
        TWO_BALCONIES_AND_TERRACE_BALCONY_TYPE
    ]

    APARTMENT_ROOM_COUNT_VALUE = 'apartment'
    ONE_ROOM_COUNT_VALUE = 'one'
    TWO_ROOM_COUNT_VALUE = 'two'
    THREE_ROOM_COUNT_VALUE = 'three'
    FOUR_ROOM_COUNT_VALUE = 'four'
    FIVE_ROOM_COUNT_VALUE = 'five'
    SIX_ROOM_COUNT_VALUE = 'six'

    ROOM_COUNT_VALUES = [
        APARTMENT_ROOM_COUNT_VALUE,
        ONE_ROOM_COUNT_VALUE,
        TWO_ROOM_COUNT_VALUE,
        THREE_ROOM_COUNT_VALUE,
        FOUR_ROOM_COUNT_VALUE,
        FIVE_ROOM_COUNT_VALUE,
        SIX_ROOM_COUNT_VALUE
    ]
