# Generated by Django 2.1.3 on 2018-11-04 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.CharField(choices=[('apartment', 'apartment'), ('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six')], max_length=15, verbose_name='Комнатность')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Цена не может быть отрицательной')], verbose_name='Цена')),
                ('area', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Площадь не может быть отрицательной')], verbose_name='Площадь')),
                ('balcony_type', models.CharField(choices=[('balcony', 'balcony'), ('loggia', 'loggia'), ('balcony_and_loggia', 'balcony_and_loggia'), ('two_balconies', 'two_balconies'), ('three_balconies', 'three_balconies'), ('four_balconies', 'four_balconies'), ('two_loggias', 'two_loggias'), ('three_loggias', 'three_loggias'), ('four_loggias', 'four_loggias'), ('five_loggias', 'five_loggias'), ('terrace', 'terrace'), ('balcony_and_terrace', 'balcony_and_terrace'), ('two_balconies_and_terrace', 'two_balconies_and_terrace')], max_length=30, verbose_name='Тип балкона')),
                ('hypothec', models.BooleanField(default=False, verbose_name='Ипотека')),
                ('military_hypothec', models.BooleanField(default=False, verbose_name='Военная ипотека')),
            ],
        ),
    ]
