# Generated by Django 2.1.3 on 2018-11-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterField(
            model_name='flat',
            name='balcony_type',
            field=models.CharField(blank=True, choices=[('balcony', 'balcony'), ('loggia', 'loggia'), ('balcony_and_loggia', 'balcony_and_loggia'), ('two_balconies', 'two_balconies'), ('three_balconies', 'three_balconies'), ('four_balconies', 'four_balconies'), ('two_loggias', 'two_loggias'), ('three_loggias', 'three_loggias'), ('four_loggias', 'four_loggias'), ('five_loggias', 'five_loggias'), ('terrace', 'terrace'), ('balcony_and_terrace', 'balcony_and_terrace'), ('two_balconies_and_terrace', 'two_balconies_and_terrace')], max_length=30, null=True, verbose_name='Тип балкона'),
        ),
    ]
